/* =========================================================
   lore-roman.js – Wissensfragen zum Römischen Reich
   Aufbau wie lore-medieval.js: richtige Antwort steht vorn.
   ========================================================= */
(function (global) {
  'use strict';
  var TD = global.TD;
  var f = TD.FACTIONS.roman;

  f.facts = f.facts.concat([
    { id: 'republic', title: 'Republik und Kaiserzeit',
      text: 'Rom war fast fünfhundert Jahre Republik, bevor Augustus die Kaiserzeit begründete. Die Formen der Republik – Senat, Konsuln – bestanden danach weiter, ohne noch viel zu entscheiden.' },
    { id: 'tribune', title: 'Der Volkstribun',
      text: 'Volkstribunen konnten Beschlüsse mit einem einzigen Wort verhindern: „veto" – ich verbiete. Ihre Person galt als unverletzlich.' },
    { id: 'rubicon', title: 'Der Rubikon',
      text: 'Mit seiner Legion den Grenzfluss Rubikon zu überschreiten, kam einer Kriegserklärung gleich. Caesar tat es 49 v. Chr. – daher die Redensart.' },
    { id: 'augustus', title: 'Augustus',
      text: 'Augustus nannte sich bescheiden „Princeps", der Erste unter Gleichen. Tatsächlich vereinte er alle wichtigen Ämter in seiner Hand.' },
    { id: 'paxromana', title: 'Die Pax Romana',
      text: 'Rund zwei Jahrhunderte lang herrschte im Inneren des Reiches weitgehend Frieden. Handel und Städtebau blühten wie nie zuvor.' },
    { id: 'gladiator', title: 'Gladiatoren',
      text: 'Gladiatoren waren teuer in Ausbildung und Unterhalt. Die meisten Kämpfe endeten deshalb nicht tödlich – ein toter Gladiator war ein teurer Verlust.' },
    { id: 'gladiatortypes', title: 'Gladiatorentypen',
      text: 'Es gab feste Typen mit eigener Ausrüstung: Der Retiarius kämpfte mit Netz und Dreizack, der Murmillo mit Schild und Kurzschwert.' },
    { id: 'circus', title: 'Der Circus Maximus',
      text: 'Bis zu 150.000 Zuschauer verfolgten die Wagenrennen. Die vier Rennställe – Rot, Weiß, Grün und Blau – hatten fanatische Anhänger.' },
    { id: 'thermae', title: 'Die Thermen',
      text: 'Thermen waren Badehaus, Sportplatz, Bibliothek und Treffpunkt zugleich. Der Eintritt war so gering, dass ihn fast jeder aufbringen konnte.' },
    { id: 'toga', title: 'Die Toga',
      text: 'Die Toga durfte nur ein römischer Bürger tragen. Sie war unbequem, schwer und ohne fremde Hilfe kaum anzulegen – Alltagskleidung war die Tunika.' },
    { id: 'slavery', title: 'Sklaverei und Freilassung',
      text: 'Freigelassene wurden römische Bürger, blieben ihrem früheren Herrn aber verpflichtet. Manche brachten es zu beträchtlichem Wohlstand.' },
    { id: 'names', title: 'Römische Namen',
      text: 'Ein römischer Mann trug drei Namen: Vorname, Familienname und Beiname. Der Beiname war oft ein Spitzname – „Cicero" heißt Kichererbse.' },
    { id: 'twelvetables', title: 'Die Zwölftafelgesetze',
      text: 'Um 450 v. Chr. wurde das Recht auf zwölf Tafeln öffentlich ausgestellt. Damit konnte sich niemand mehr auf geheimes Wissen berufen.' },
    { id: 'diploma', title: 'Militärdiplome',
      text: 'Nach fünfundzwanzig Dienstjahren erhielten Hilfstruppensoldaten das Bürgerrecht – bescheinigt auf zwei Bronzetafeln, die sie ihr Leben lang aufbewahrten.' },
    { id: 'silk', title: 'Handel bis Indien',
      text: 'Römische Münzen wurden in Indien gefunden. Seide kam über Zwischenhändler aus China – so teuer, dass der Senat ihr Tragen zeitweise rügte.' },
    { id: 'coins', title: 'Denar und Sesterz',
      text: 'Der silberne Denar war der Grundpfeiler des Münzwesens. Ein Legionär verdiente unter Augustus etwa 225 Denare im Jahr.' },
    { id: 'annona', title: 'Die Getreideversorgung',
      text: 'Ägypten war die Kornkammer Roms. Ein eigener Beamter sorgte für die Annona – die Versorgung der Hauptstadt mit Getreide.' },
    { id: 'insula', title: 'Die Insula',
      text: 'Die meisten Römer wohnten in mehrstöckigen Mietshäusern, den Insulae. Je höher die Wohnung, desto billiger – und desto gefährlicher bei Feuer.' },
    { id: 'villa', title: 'Die Villa rustica',
      text: 'Die Villa rustica war ein Landgut mit Wohnhaus und Wirtschaftsgebäuden. Sie versorgte die Städte mit Wein, Öl und Getreide.' },
    { id: 'mosaic', title: 'Mosaike',
      text: 'Fußböden wurden aus winzigen Steinchen zusammengesetzt. Ein beliebtes Motiv am Hauseingang: ein Hund mit der Warnung „Cave canem".' },
    { id: 'mithras', title: 'Der Mithraskult',
      text: 'Der Mithraskult war bei Soldaten beliebt und nahm nur Männer auf. Seine Heiligtümer lagen unter der Erde und waren bewusst eng gehalten.' },
    { id: 'vestal', title: 'Die Vestalinnen',
      text: 'Die Vestalinnen hüteten das heilige Feuer Roms. Sie genossen Vorrechte, die sonst keine Frau hatte – erloschen ließen sie das Feuer, drohte schwere Strafe.' },
    { id: 'triumph', title: 'Der Triumphzug',
      text: 'Beim Triumphzug fuhr der Feldherr durch Rom, das Gesicht rot bemalt wie eine Götterstatue. Ein Sklave hielt den Kranz und mahnte ihn, ein Mensch zu bleiben.' },
    { id: 'lasmedulas', title: 'Ruina montium',
      text: 'In Las Médulas leiteten Ingenieure Wasser in Stollen und sprengten ganze Berge auseinander, um an Gold zu kommen. Die Landschaft trägt die Spuren bis heute.' },
    { id: 'lighthouse', title: 'Leuchttürme',
      text: 'Der Leuchtturm von La Coruña steht seit fast zweitausend Jahren und ist bis heute in Betrieb – der älteste noch arbeitende Leuchtturm der Welt.' },
    { id: 'cursus', title: 'Der Cursus publicus',
      text: 'Ein staatlicher Nachrichtendienst mit Pferdewechselstationen brachte Botschaften bis zu 80 Kilometer am Tag voran.' },
    { id: 'census', title: 'Der Zensus',
      text: 'Alle fünf Jahre wurden Bürger und Vermögen erfasst. Vom lateinischen „census" stammt unser Wort Zensur – die Censoren wachten auch über die Sitten.' },
    { id: 'hadrianswall', title: 'Der Hadrianswall',
      text: 'Über 117 Kilometer zog sich der Hadrianswall quer durch Britannien. Er war weniger Bollwerk als Kontrollpunkt für Handel und Wanderung.' },
    { id: 'varus', title: 'Die Varusschlacht',
      text: '9 n. Chr. gingen drei Legionen im Germanien verloren. Rom gab die Eroberung östlich des Rheins daraufhin praktisch auf.' },
    { id: 'constantine', title: 'Konstantin',
      text: 'Konstantin beendete 313 die Christenverfolgung. Getauft wurde er selbst erst auf dem Sterbebett.' },
    { id: 'byzantium', title: 'Das Reich, das blieb',
      text: 'Das Weströmische Reich endete 476. Das Oströmische bestand als Byzanz noch fast tausend Jahre weiter – bis 1453.' }
  ]);

  f.questions = f.questions.concat([
    { fact: 'republic', q: 'Wie lange war Rom Republik, bevor die Kaiserzeit begann?', answers: ['Fast fünfhundert Jahre', 'Etwa hundert Jahre', 'Rund tausend Jahre', 'Nur fünfzig Jahre'], correct: 0 },
    { fact: 'tribune', q: 'Mit welchem Wort konnte ein Volkstribun Beschlüsse verhindern?', answers: ['Veto', 'Ave', 'Salve', 'Vale'], correct: 0 },
    { fact: 'tribune', q: 'Was galt für die Person eines Volkstribunen?', answers: ['Sie war unverletzlich', 'Sie war steuerfrei', 'Sie durfte nicht heiraten', 'Sie musste in Rom bleiben'], correct: 0 },
    { fact: 'rubicon', q: 'Was bedeutete es, mit einem Heer den Rubikon zu überschreiten?', answers: ['Es kam einer Kriegserklärung gleich', 'Man betrat heiligen Boden', 'Man verließ das Reich', 'Man durfte nicht mehr zurück nach Gallien'], correct: 0 },
    { fact: 'rubicon', q: 'In welchem Jahr überschritt Caesar den Rubikon?', answers: ['49 v. Chr.', '44 v. Chr.', '31 v. Chr.', '58 v. Chr.'], correct: 0 },
    { fact: 'augustus', q: 'Wie nannte sich Augustus selbst?', answers: ['Princeps – der Erste unter Gleichen', 'Rex – König', 'Dominus – Herr', 'Imperator Maximus'], correct: 0 },
    { fact: 'paxromana', q: 'Was kennzeichnete die Pax Romana?', answers: ['Rund zwei Jahrhunderte inneren Frieden', 'Den Verzicht auf ein Heer', 'Ein Bündnis mit Karthago', 'Die Abschaffung der Sklaverei'], correct: 0 },
    { fact: 'gladiator', q: 'Warum endeten die meisten Gladiatorenkämpfe nicht tödlich?', answers: ['Gladiatoren waren teuer in Ausbildung und Unterhalt', 'Es war gesetzlich verboten', 'Die Zuschauer verlangten es so', 'Die Waffen waren stumpf'], correct: 0 },
    { fact: 'gladiatortypes', q: 'Womit kämpfte der Retiarius?', answers: ['Mit Netz und Dreizack', 'Mit Schild und Kurzschwert', 'Mit Bogen und Pfeil', 'Mit zwei Dolchen'], correct: 0 },
    { fact: 'circus', q: 'Wie viele Zuschauer fasste der Circus Maximus?', answers: ['Bis zu 150.000', 'Etwa 5.000', 'Rund 50.000', 'Über eine Million'], correct: 0 },
    { fact: 'circus', q: 'Wie viele Rennställe traten im Circus gegeneinander an?', answers: ['Vier: Rot, Weiß, Grün und Blau', 'Zwei: Rot und Blau', 'Sechs', 'Zehn'], correct: 0 },
    { fact: 'thermae', q: 'Was fand man in römischen Thermen außer Bädern?', answers: ['Sportplatz, Bibliothek und Treffpunkt', 'Nur Umkleiden', 'Eine Kaserne', 'Gerichtssäle'], correct: 0 },
    { fact: 'toga', q: 'Wer durfte eine Toga tragen?', answers: ['Nur römische Bürger', 'Jeder Einwohner', 'Nur Senatoren', 'Nur Priester'], correct: 0 },
    { fact: 'toga', q: 'Was trugen Römer im Alltag?', answers: ['Die Tunika', 'Die Toga', 'Den Umhang der Legionäre', 'Ein Lendentuch'], correct: 0 },
    { fact: 'slavery', q: 'Was wurde aus einem freigelassenen Sklaven?', answers: ['Ein römischer Bürger mit Pflichten gegenüber dem früheren Herrn', 'Ein Sklave zweiter Klasse', 'Ein Ausländer ohne Rechte', 'Ein Mitglied des Senats'], correct: 0 },
    { fact: 'names', q: 'Wie viele Namen trug ein römischer Mann üblicherweise?', answers: ['Drei', 'Einen', 'Zwei', 'Fünf'], correct: 0 },
    { fact: 'names', q: 'Was bedeutet der Beiname „Cicero"?', answers: ['Kichererbse', 'Redner', 'Löwenherz', 'Der Gerechte'], correct: 0 },
    { fact: 'twelvetables', q: 'Was war das Besondere an den Zwölftafelgesetzen?', answers: ['Das Recht war öffentlich einsehbar', 'Sie galten nur für Patrizier', 'Sie wurden geheim gehalten', 'Sie schafften die Todesstrafe ab'], correct: 0 },
    { fact: 'diploma', q: 'Was erhielten Hilfstruppensoldaten nach 25 Dienstjahren?', answers: ['Das römische Bürgerrecht', 'Ein Landgut in Italien', 'Einen Sitz im Senat', 'Lebenslangen Sold'], correct: 0 },
    { fact: 'silk', q: 'Woher kam die Seide, die Rom erreichte?', answers: ['Über Zwischenhändler aus China', 'Aus Ägypten', 'Aus Gallien', 'Aus Persien, wo sie hergestellt wurde'], correct: 0 },
    { fact: 'silk', q: 'Was belegt römische Münzfunde in Indien?', answers: ['Weitreichende Handelsbeziehungen', 'Eine römische Eroberung', 'Eine Auswanderungswelle', 'Eine Fälscherwerkstatt'], correct: 0 },
    { fact: 'coins', q: 'Welche Münze war der Grundpfeiler des römischen Münzwesens?', answers: ['Der silberne Denar', 'Der goldene Aureus', 'Der bronzene As', 'Die Drachme'], correct: 0 },
    { fact: 'annona', q: 'Welche Provinz war die Kornkammer Roms?', answers: ['Ägypten', 'Gallien', 'Britannien', 'Dakien'], correct: 0 },
    { fact: 'insula', q: 'Wo wohnten die meisten Römer?', answers: ['In mehrstöckigen Mietshäusern', 'In eigenen Stadthäusern', 'In Villen vor der Stadt', 'In Kasernen'], correct: 0 },
    { fact: 'insula', q: 'Welche Wohnungen in einer Insula waren am billigsten?', answers: ['Die obersten', 'Die im Erdgeschoss', 'Die zum Innenhof', 'Alle kosteten gleich viel'], correct: 0 },
    { fact: 'villa', q: 'Was war eine Villa rustica?', answers: ['Ein Landgut mit Wohn- und Wirtschaftsgebäuden', 'Ein Stadtpalast', 'Ein Tempelbezirk', 'Eine Herberge an der Straße'], correct: 0 },
    { fact: 'mosaic', q: 'Was bedeutet die Mosaikinschrift „Cave canem"?', answers: ['Hüte dich vor dem Hund', 'Willkommen im Haus', 'Betreten verboten', 'Hier wohnt Glück'], correct: 0 },
    { fact: 'mithras', q: 'Wer durfte dem Mithraskult beitreten?', answers: ['Nur Männer', 'Nur Frauen', 'Nur Senatoren', 'Jeder Bürger'], correct: 0 },
    { fact: 'mithras', q: 'Wo lagen die Heiligtümer des Mithras?', answers: ['Unter der Erde', 'Auf Hügelkuppen', 'Am Flussufer', 'Im Zentrum des Forums'], correct: 0 },
    { fact: 'vestal', q: 'Was war die Aufgabe der Vestalinnen?', answers: ['Sie hüteten das heilige Feuer Roms', 'Sie berieten den Senat', 'Sie verwalteten die Getreidespeicher', 'Sie unterrichteten die Kinder'], correct: 0 },
    { fact: 'triumph', q: 'Was tat ein Sklave beim Triumphzug hinter dem Feldherrn?', answers: ['Er hielt den Kranz und mahnte ihn, ein Mensch zu bleiben', 'Er trug die Beute', 'Er verteilte Münzen', 'Er führte die Pferde'], correct: 0 },
    { fact: 'triumph', q: 'Wie war das Gesicht des Triumphators bemalt?', answers: ['Rot, wie eine Götterstatue', 'Weiß, wie ein Priester', 'Gar nicht', 'Golden'], correct: 0 },
    { fact: 'lasmedulas', q: 'Wie gewannen die Römer in Las Médulas Gold?', answers: ['Sie sprengten Berge mit eingeleitetem Wasser', 'Sie wuschen es aus dem Fluss', 'Sie ließen Sklaven Schächte graben', 'Sie handelten es ein'], correct: 0 },
    { fact: 'lighthouse', q: 'Was ist am Leuchtturm von La Coruña besonders?', answers: ['Er ist der älteste noch arbeitende Leuchtturm der Welt', 'Er ist der höchste Turm der Antike', 'Er wurde nie fertiggestellt', 'Er stand auf einer Insel'], correct: 0 },
    { fact: 'cursus', q: 'Wie weit kam eine Nachricht im Cursus publicus am Tag?', answers: ['Bis zu 80 Kilometer', 'Etwa 10 Kilometer', 'Rund 300 Kilometer', 'Nur 5 Kilometer'], correct: 0 },
    { fact: 'census', q: 'Wie oft wurde der Zensus durchgeführt?', answers: ['Alle fünf Jahre', 'Jedes Jahr', 'Alle zwanzig Jahre', 'Nur bei Regierungswechsel'], correct: 0 },
    { fact: 'census', q: 'Welches heutige Wort geht auf den römischen Zensus zurück?', answers: ['Zensur', 'Zins', 'Zentrum', 'Zenit'], correct: 0 },
    { fact: 'hadrianswall', q: 'Wie lang war der Hadrianswall?', answers: ['Über 117 Kilometer', 'Rund 20 Kilometer', 'Etwa 500 Kilometer', 'Knapp 60 Kilometer'], correct: 0 },
    { fact: 'hadrianswall', q: 'Welchen Zweck erfüllte der Hadrianswall vor allem?', answers: ['Er war Kontrollpunkt für Handel und Wanderung', 'Er hielt eine Belagerung aus', 'Er diente als Wasserleitung', 'Er markierte eine heilige Grenze'], correct: 0 },
    { fact: 'varus', q: 'Was geschah 9 n. Chr. in Germanien?', answers: ['Drei Legionen gingen verloren', 'Rom eroberte Germanien', 'Ein Friedensvertrag wurde geschlossen', 'Der Limes wurde vollendet'], correct: 0 },
    { fact: 'varus', q: 'Welche Folge hatte die Varusschlacht?', answers: ['Rom gab die Eroberung östlich des Rheins auf', 'Der Kaiser dankte ab', 'Germanien wurde Provinz', 'Die Legionen wurden verdoppelt'], correct: 0 },
    { fact: 'constantine', q: 'Was beendete Konstantin im Jahr 313?', answers: ['Die Christenverfolgung', 'Die Sklaverei', 'Die Gladiatorenkämpfe', 'Die Teilung des Reiches'], correct: 0 },
    { fact: 'constantine', q: 'Wann ließ sich Konstantin taufen?', answers: ['Erst auf dem Sterbebett', 'Als Kind', 'Bei seiner Krönung', 'Gar nicht'], correct: 0 },
    { fact: 'byzantium', q: 'Wann endete das Weströmische Reich?', answers: ['476', '395', '1453', '312'], correct: 0 },
    { fact: 'byzantium', q: 'Bis wann bestand das Oströmische Reich?', answers: ['Bis 1453', 'Bis 476', 'Bis 800', 'Bis 1066'], correct: 0 },
    { fact: 'gladiator', q: 'Was bedeutete der Tod eines Gladiators für seinen Besitzer?', answers: ['Einen teuren Verlust', 'Einen Gewinn durch Wetten', 'Eine Ehre', 'Nichts Besonderes'], correct: 0 },
    { fact: 'thermae', q: 'Wie hoch war der Eintritt in die Thermen?', answers: ['So gering, dass ihn fast jeder aufbringen konnte', 'Ein Tageslohn', 'Nur für Senatoren erschwinglich', 'Er war stets kostenlos'], correct: 0 },
    { fact: 'annona', q: 'Wie hieß die Getreideversorgung der Hauptstadt?', answers: ['Annona', 'Cursus', 'Census', 'Congiarium'], correct: 0 },
    { fact: 'coins', q: 'Wie viel verdiente ein Legionär unter Augustus etwa im Jahr?', answers: ['Rund 225 Denare', 'Etwa 20 Denare', 'Über 2.000 Denare', 'Er erhielt keinen Sold'], correct: 0 }
  ]);
})(window);
