/* =========================================================
   lore-viking.js – Wissensfragen zur Welt der Nordleute
   Aufbau wie lore-medieval.js: richtige Antwort steht vorn.
   ========================================================= */
(function (global) {
  'use strict';
  var TD = global.TD;
  var f = TD.FACTIONS.viking;

  f.facts = f.facts.concat([
    { id: 'odin', title: 'Odin',
      text: 'Odin gab ein Auge, um aus dem Brunnen der Weisheit trinken zu dürfen. Zwei Raben, Hugin und Munin, fliegen täglich aus und berichten ihm von der Welt.' },
    { id: 'thor', title: 'Thor und Mjölnir',
      text: 'Thors Hammer Mjölnir kehrte nach jedem Wurf in seine Hand zurück. Kleine Hammeranhänger waren als Schmuck weit verbreitet.' },
    { id: 'yggdrasil', title: 'Yggdrasil',
      text: 'Der Weltenbaum Yggdrasil verbindet neun Welten. An seinen Wurzeln nagt der Drache Nidhöggr, in seinen Zweigen sitzt ein Adler.' },
    { id: 'valhalla', title: 'Walhall',
      text: 'In Odins Halle Walhall kämpfen die gefallenen Krieger täglich und feiern jeden Abend. Sie rüsten sich für die Schlacht bei Ragnarök.' },
    { id: 'valkyrie', title: 'Die Walküren',
      text: 'Walküren wählten auf dem Schlachtfeld aus, wer fällt – und geleiteten die Würdigen nach Walhall. Ihr Name bedeutet „die Wahl der Erschlagenen".' },
    { id: 'loki', title: 'Loki',
      text: 'Loki ist weder ganz Gott noch ganz Riese. Er bringt die Götter in Schwierigkeiten und rettet sie ebenso oft wieder heraus.' },
    { id: 'jormungandr', title: 'Die Midgardschlange',
      text: 'Jörmungandr umspannt die ganze Welt und beißt sich in den eigenen Schwanz. Lässt sie los, beginnt Ragnarök.' },
    { id: 'sleipnir', title: 'Sleipnir',
      text: 'Odins Pferd Sleipnir hat acht Beine und trägt seinen Reiter über Land, Meer und bis in die Totenwelt.' },
    { id: 'burial', title: 'Schiffsbestattung',
      text: 'Bedeutende Tote wurden in Schiffen bestattet, mit Waffen, Vorräten und Werkzeug. Manche Schiffe wurden verbrannt, andere unter einem Hügel begraben.' },
    { id: 'longhouse', title: 'Das Langhaus',
      text: 'Ein Langhaus beherbergte Menschen und Vieh unter einem Dach. Die Wände bestanden oft aus Grassoden, die hervorragend dämmten.' },
    { id: 'haithabu', title: 'Haithabu und Birka',
      text: 'Haithabu an der Schlei und Birka im Mälarsee waren große Handelsplätze. Dort trafen Waren aus dem Frankenreich, dem Orient und dem Norden zusammen.' },
    { id: 'rus', title: 'Der Weg nach Osten',
      text: 'Über russische Flüsse fuhren die Nordleute bis ans Schwarze Meer. Die Rus gaben Russland seinen Namen.' },
    { id: 'greenland', title: 'Erik der Rote',
      text: 'Erik der Rote wurde aus Island verbannt und besiedelte Grönland. Den einladenden Namen wählte er, um Siedler anzulocken.' },
    { id: 'iceland', title: 'Die Besiedlung Islands',
      text: 'Um 870 begann die Besiedlung Islands. Das Landnahmebuch verzeichnet die ersten Siedler mit Namen und Hofstelle.' },
    { id: 'sagas', title: 'Die Sagas',
      text: 'Die isländischen Sagas wurden erst im 13. Jahrhundert aufgeschrieben – Jahrhunderte nach den Ereignissen, von denen sie erzählen.' },
    { id: 'edda', title: 'Die Edda',
      text: 'Die Lieder-Edda sammelt alte Götterdichtung, die Snorra-Edda erklärt sie. Ohne Snorri Sturluson wüssten wir weit weniger über die nordischen Mythen.' },
    { id: 'hnefatafl', title: 'Hnefatafl',
      text: 'Beim Brettspiel Hnefatafl verteidigte eine kleinere Partei ihren König gegen doppelte Übermacht. Spielsteine fand man in vielen Gräbern.' },
    { id: 'wergeld', title: 'Das Wergeld',
      text: 'Statt Gefängnis gab es Bußzahlungen. Für jede Verletzung und jeden Todesfall war ein Betrag festgelegt – abgestuft nach Stand des Opfers.' },
    { id: 'holmgang', title: 'Der Holmgang',
      text: 'Streit ließ sich im Zweikampf entscheiden, dem Holmgang. Er fand auf einer abgesteckten Fläche statt und folgte festen Regeln.' },
    { id: 'outlaw', title: 'Die Friedloserklärung',
      text: 'Die härteste Strafe war die Ächtung: Der Verurteilte verlor jeden Rechtsschutz. Ihn zu töten war straffrei.' },
    { id: 'birka', title: 'Das Kriegergrab von Birka',
      text: 'Ein reich ausgestattetes Kriegergrab in Birka galt lange als das eines Mannes. Eine Untersuchung des Erbguts zeigte 2017: Die Bestattete war eine Frau.' },
    { id: 'danegeld', title: 'Das Danegeld',
      text: 'Englische Könige zahlten hohe Summen, damit die Nordleute abzogen. Das Geld finanzierte oft nur die nächste Fahrt.' },
    { id: 'cnut', title: 'Knut der Große',
      text: 'Knut der Große herrschte zugleich über England, Dänemark und Norwegen. Sein Nordseereich zerfiel kurz nach seinem Tod.' },
    { id: 'stamford', title: '1066',
      text: 'Bei Stamford Bridge unterlag Harald Hardrada dem englischen König. Wenige Tage später verlor dieser gegen Wilhelm den Eroberer – die Wikingerzeit ging zu Ende.' },
    { id: 'christian', title: 'Die Christianisierung',
      text: 'Der Übergang zum Christentum dauerte Generationen. Manche Anhänger trugen Kreuz und Thorshammer zugleich – sicher ist sicher.' },
    { id: 'runestone', title: 'Runensteine',
      text: 'Runensteine wurden meist zum Gedenken an Verstorbene errichtet. Viele standen an Wegen, wo möglichst viele sie lesen konnten.' },
    { id: 'knarr', title: 'Knorr und Langschiff',
      text: 'Das Langschiff war schmal und schnell, die Knorr breit und bauchig. Für Handelsfahrten nahm man die Knorr, für Raubzüge das Langschiff.' },
    { id: 'sail', title: 'Segel aus Wolle',
      text: 'Segel wurden aus Wolle gewebt und mit Fett imprägniert. Ein einziges Segel verbrauchte die Wolle von Hunderten Schafen und Jahre an Arbeit.' },
    { id: 'sunstone', title: 'Peilscheibe und Sonnenstein',
      text: 'Eine Peilscheibe zeigte über den Schattenwurf die Richtung an. Ob auch der viel diskutierte „Sonnenstein" genutzt wurde, ist bis heute umstritten.' },
    { id: 'skis', title: 'Ski und Schlitten',
      text: 'Im Winter bewegte man sich auf Skiern fort – Funde reichen Jahrtausende zurück. Der Gott Ullr galt als Schutzherr der Skiläufer.' }
  ]);

  f.questions = f.questions.concat([
    { fact: 'odin', q: 'Was gab Odin für einen Schluck aus dem Brunnen der Weisheit?', answers: ['Ein Auge', 'Eine Hand', 'Seinen Speer', 'Sein Pferd'], correct: 0 },
    { fact: 'odin', q: 'Wie heißen Odins Raben?', answers: ['Hugin und Munin', 'Geri und Freki', 'Skoll und Hati', 'Nidhögg und Ratatöskr'], correct: 0 },
    { fact: 'thor', q: 'Was war das Besondere an Thors Hammer?', answers: ['Er kehrte nach dem Wurf zurück', 'Er war unsichtbar', 'Er wuchs im Kampf', 'Er konnte sprechen'], correct: 0 },
    { fact: 'thor', q: 'Welcher Schmuck war bei den Nordleuten verbreitet?', answers: ['Kleine Thorshammer-Anhänger', 'Silberne Raben', 'Bernsteinkronen', 'Eiserne Ringe am Fuß'], correct: 0 },
    { fact: 'yggdrasil', q: 'Was ist Yggdrasil?', answers: ['Der Weltenbaum, der neun Welten verbindet', 'Odins Speer', 'Die Halle der Gefallenen', 'Ein heiliger Fluss'], correct: 0 },
    { fact: 'yggdrasil', q: 'Wer nagt an den Wurzeln des Weltenbaums?', answers: ['Der Drache Nidhöggr', 'Die Midgardschlange', 'Fenrir', 'Ein Eichhörnchen'], correct: 0 },
    { fact: 'valhalla', q: 'Was tun die Krieger in Walhall den ganzen Tag?', answers: ['Sie kämpfen und feiern abends', 'Sie ruhen sich aus', 'Sie bauen Schiffe', 'Sie dichten Verse'], correct: 0 },
    { fact: 'valhalla', q: 'Worauf bereiten sich die Einherjer vor?', answers: ['Auf die Schlacht bei Ragnarök', 'Auf die Rückkehr ins Leben', 'Auf eine Fahrt nach Vinland', 'Auf das Thing der Götter'], correct: 0 },
    { fact: 'valkyrie', q: 'Was war die Aufgabe der Walküren?', answers: ['Sie wählten die Gefallenen aus und geleiteten sie', 'Sie heilten Verwundete', 'Sie bewachten Odins Halle', 'Sie schmiedeten Waffen'], correct: 0 },
    { fact: 'loki', q: 'Was trifft auf Loki zu?', answers: ['Er ist weder ganz Gott noch ganz Riese', 'Er ist Odins Vater', 'Er herrscht über Walhall', 'Er ist der Gott des Ackerbaus'], correct: 0 },
    { fact: 'jormungandr', q: 'Was tut die Midgardschlange?', answers: ['Sie umspannt die Welt und beißt in ihren Schwanz', 'Sie bewacht den Weltenbaum', 'Sie zieht Odins Wagen', 'Sie schläft unter Island'], correct: 0 },
    { fact: 'jormungandr', q: 'Was geschieht, wenn Jörmungandr loslässt?', answers: ['Ragnarök beginnt', 'Die Sonne erlischt', 'Der Fimbulwinter endet', 'Walhall öffnet sich'], correct: 0 },
    { fact: 'sleipnir', q: 'Wie viele Beine hat Odins Pferd Sleipnir?', answers: ['Acht', 'Vier', 'Sechs', 'Zwölf'], correct: 0 },
    { fact: 'burial', q: 'Was gab man Toten bei einer Schiffsbestattung mit?', answers: ['Waffen, Vorräte und Werkzeug', 'Nur ein Schwert', 'Ausschließlich Schmuck', 'Nichts, das Schiff genügte'], correct: 0 },
    { fact: 'longhouse', q: 'Wer lebte gemeinsam in einem Langhaus?', answers: ['Menschen und Vieh unter einem Dach', 'Nur der Jarl und seine Wache', 'Ausschließlich unverheiratete Männer', 'Die Priester des Ortes'], correct: 0 },
    { fact: 'longhouse', q: 'Woraus bestanden die Wände vieler Langhäuser?', answers: ['Aus Grassoden', 'Aus behauenem Stein', 'Aus gebrannten Ziegeln', 'Aus Lehmziegeln'], correct: 0 },
    { fact: 'haithabu', q: 'Was waren Haithabu und Birka?', answers: ['Große Handelsplätze', 'Königsgräber', 'Heilige Haine', 'Festungen gegen die Franken'], correct: 0 },
    { fact: 'rus', q: 'Welchem Land gaben die Rus ihren Namen?', answers: ['Russland', 'Rumänien', 'Preußen', 'Ruthenien allein'], correct: 0 },
    { fact: 'rus', q: 'Bis wohin fuhren die Nordleute über russische Flüsse?', answers: ['Bis ans Schwarze Meer', 'Bis zum Ural', 'Bis nach China', 'Nur bis Nowgorod'], correct: 0 },
    { fact: 'greenland', q: 'Warum nannte Erik der Rote das Land „Grünland"?', answers: ['Um Siedler anzulocken', 'Wegen der grünen Gletscher', 'Nach seiner Mutter', 'Es war ein Schreibfehler'], correct: 0 },
    { fact: 'greenland', q: 'Warum verließ Erik der Rote Island?', answers: ['Er wurde verbannt', 'Er suchte Handelswege', 'Er floh vor der Pest', 'Der König schickte ihn'], correct: 0 },
    { fact: 'iceland', q: 'Wann begann die Besiedlung Islands?', answers: ['Um 870', 'Um 1100', 'Um 600', 'Um 1250'], correct: 0 },
    { fact: 'iceland', q: 'Was verzeichnet das Landnahmebuch?', answers: ['Die ersten Siedler mit Namen und Hof', 'Die Gesetze des Althing', 'Die Königsreihe Norwegens', 'Alle Runensteine der Insel'], correct: 0 },
    { fact: 'sagas', q: 'Wann wurden die isländischen Sagas aufgeschrieben?', answers: ['Im 13. Jahrhundert', 'Im 9. Jahrhundert', 'Im 16. Jahrhundert', 'Erst im 19. Jahrhundert'], correct: 0 },
    { fact: 'edda', q: 'Wem verdanken wir einen Großteil unseres Wissens über nordische Mythen?', answers: ['Snorri Sturluson', 'Saxo Grammaticus', 'Adam von Bremen', 'Ari dem Weisen'], correct: 0 },
    { fact: 'hnefatafl', q: 'Worum ging es beim Brettspiel Hnefatafl?', answers: ['Eine kleinere Partei verteidigt ihren König', 'Zwei gleich starke Heere kämpfen', 'Man sammelt Handelsgüter', 'Man zieht Schiffe um eine Insel'], correct: 0 },
    { fact: 'wergeld', q: 'Was war das Wergeld?', answers: ['Eine festgelegte Bußzahlung für Verletzung oder Tötung', 'Der Sold eines Kriegers', 'Eine Abgabe an den Jarl', 'Der Preis eines Schiffes'], correct: 0 },
    { fact: 'wergeld', q: 'Wonach richtete sich die Höhe des Wergelds?', answers: ['Nach dem Stand des Opfers', 'Nach dem Alter des Täters', 'Nach der Jahreszeit', 'Es war für alle gleich'], correct: 0 },
    { fact: 'holmgang', q: 'Was war ein Holmgang?', answers: ['Ein geregelter Zweikampf zur Streitentscheidung', 'Eine Beratung am Strand', 'Ein Handelstreffen', 'Ein Opferritual'], correct: 0 },
    { fact: 'outlaw', q: 'Was bedeutete die Friedloserklärung?', answers: ['Der Verurteilte verlor jeden Rechtsschutz', 'Er musste sieben Jahre dienen', 'Sein Besitz wurde halbiert', 'Er durfte nicht mehr sprechen'], correct: 0 },
    { fact: 'birka', q: 'Was ergab die Untersuchung des Kriegergrabs von Birka 2017?', answers: ['Die Bestattete war eine Frau', 'Es war ein Kenotaph ohne Leichnam', 'Der Tote stammte aus Byzanz', 'Die Waffen waren Grabbeigaben eines anderen'], correct: 0 },
    { fact: 'danegeld', q: 'Wofür zahlten englische Könige das Danegeld?', answers: ['Damit die Nordleute abzogen', 'Für Schiffe aus Norwegen', 'Als Mitgift', 'Für den Bau von Kirchen'], correct: 0 },
    { fact: 'cnut', q: 'Über welche Länder herrschte Knut der Große zugleich?', answers: ['England, Dänemark und Norwegen', 'Island, Grönland und Irland', 'Schweden, Finnland und Russland', 'Normandie, England und Schottland'], correct: 0 },
    { fact: 'stamford', q: 'Welches Jahr gilt als Ende der Wikingerzeit?', answers: ['1066', '1000', '1100', '793'], correct: 0 },
    { fact: 'christian', q: 'Was trugen manche Nordleute während der Christianisierung gleichzeitig?', answers: ['Kreuz und Thorshammer', 'Zwei Kreuze', 'Runen und Kreuz auf der Stirn', 'Nichts von beidem'], correct: 0 },
    { fact: 'runestone', q: 'Wozu wurden Runensteine meist errichtet?', answers: ['Zum Gedenken an Verstorbene', 'Als Grenzmarkierung', 'Als Opferaltar', 'Als Wegweiser zum Thing'], correct: 0 },
    { fact: 'knarr', q: 'Welches Schiff nahm man für Handelsfahrten?', answers: ['Die breite Knorr', 'Das schmale Langschiff', 'Das Ruderboot', 'Die Fähre'], correct: 0 },
    { fact: 'knarr', q: 'Was zeichnete das Langschiff aus?', answers: ['Es war schmal und schnell', 'Es hatte den größten Laderaum', 'Es fuhr nur mit Rudern', 'Es war das einzige mit Segel'], correct: 0 },
    { fact: 'sail', q: 'Woraus bestanden die Segel der Nordleute?', answers: ['Aus Wolle, mit Fett imprägniert', 'Aus Leinen', 'Aus gegerbtem Leder', 'Aus Baumwolle aus dem Süden'], correct: 0 },
    { fact: 'sail', q: 'Wie aufwendig war die Herstellung eines Segels?', answers: ['Es verbrauchte die Wolle Hunderter Schafe', 'Es war in wenigen Tagen fertig', 'Man kaufte sie meist fertig ein', 'Ein Segel hielt nur eine Fahrt'], correct: 0 },
    { fact: 'sunstone', q: 'Was ist über den „Sonnenstein" bekannt?', answers: ['Seine Nutzung ist bis heute umstritten', 'Er wurde in jedem Schiff gefunden', 'Er bestand aus Bernstein', 'Er zeigte magnetisch nach Norden'], correct: 0 },
    { fact: 'skis', q: 'Welcher Gott galt als Schutzherr der Skiläufer?', answers: ['Ullr', 'Njörd', 'Baldur', 'Tyr'], correct: 0 },
    { fact: 'valkyrie', q: 'Was bedeutet der Name „Walküre"?', answers: ['Die Wahl der Erschlagenen', 'Die Tochter des Windes', 'Die Reiterin der Wolken', 'Die Hüterin der Halle'], correct: 0 },
    { fact: 'burial', q: 'Wie wurden manche Bestattungsschiffe behandelt?', answers: ['Sie wurden verbrannt oder unter einem Hügel begraben', 'Sie wurden aufs offene Meer geschickt', 'Sie wurden zerlegt und verteilt', 'Sie blieben am Ufer stehen'], correct: 0 },
    { fact: 'haithabu', q: 'Woher kamen die Waren, die in Haithabu zusammentrafen?', answers: ['Aus dem Frankenreich, dem Orient und dem Norden', 'Nur aus Skandinavien', 'Ausschließlich aus England', 'Aus China über die Seidenstraße'], correct: 0 },
    { fact: 'edda', q: 'Was unterscheidet Lieder-Edda und Snorra-Edda?', answers: ['Die eine sammelt Dichtung, die andere erklärt sie', 'Die eine ist älter, die andere gefälscht', 'Beide sind identisch', 'Die eine ist in Runen geschrieben'], correct: 0 },
    { fact: 'stamford', q: 'Wer unterlag bei Stamford Bridge?', answers: ['Harald Hardrada', 'Wilhelm der Eroberer', 'Knut der Große', 'Harald Blauzahn'], correct: 0 },
    { fact: 'odin', q: 'Was tun Hugin und Munin für Odin?', answers: ['Sie fliegen aus und berichten ihm von der Welt', 'Sie bewachen Walhall', 'Sie ziehen seinen Wagen', 'Sie holen die Gefallenen'], correct: 0 },
    { fact: 'iceland', q: 'Was gilt als eines der ältesten Parlamente und wurde auf Island gegründet?', answers: ['Das Althing', 'Der Holmgang', 'Das Wergeld', 'Die Landnahme'], correct: 0 }
  ]);
})(window);
