/* =========================================================
   lore-japan.js – Wissensfragen zum alten Japan
   Aufbau wie lore-medieval.js: richtige Antwort steht vorn.
   ========================================================= */
(function (global) {
  'use strict';
  var TD = global.TD;
  var f = TD.FACTIONS.japan;

  f.facts = f.facts.concat([
    { id: 'yokai', title: 'Yōkai',
      text: 'Yōkai ist der Sammelbegriff für die Wesen der japanischen Geisterwelt – vom scheuen Waldgeist bis zum Dämon. Viele sind weniger böse als schlicht unberechenbar.' },
    { id: 'kappa', title: 'Der Kappa',
      text: 'Der Kappa trägt eine wassergefüllte Schale auf dem Kopf, in der seine Kraft steckt. Wer sich vor ihm verneigt, den zwingt die Höflichkeit zurückzugrüßen – und dabei schwappt das Wasser heraus.' },
    { id: 'kitsune', title: 'Der Fuchsgeist',
      text: 'Ein Kitsune gewinnt mit jedem Jahrhundert einen weiteren Schwanz. Mit neun ist er weise, mächtig – und ein meisterhafter Verwandlungskünstler.' },
    { id: 'tengu', title: 'Tengu',
      text: 'Tengu hausen in den Bergen und gelten als unübertroffene Fechter. Der Sage nach lernte der junge Minamoto no Yoshitsune das Schwertkämpfen von ihnen.' },
    { id: 'oni', title: 'Oni',
      text: 'Oni sind hörnertragende Dämonen mit eiserner Keule. Beim Frühlingsfest Setsubun wirft man geröstete Sojabohnen und ruft: „Oni raus, Glück herein!"' },
    { id: 'orochi', title: 'Yamata no Orochi',
      text: 'Die achtköpfige Schlange forderte jedes Jahr ein Mädchen. Susanoo betäubte sie mit acht Fässern Reiswein und erschlug sie – im Schwanz fand er ein Schwert.' },
    { id: 'kusanagi', title: 'Kusanagi',
      text: 'Das Schwert aus Orochis Schwanz heißt Kusanagi und gehört zu den drei Reichsinsignien Japans: Schwert, Spiegel und Krummjuwel.' },
    { id: 'komainu', title: 'Komainu',
      text: 'Vor Schreinen stehen paarweise Löwenhunde. Einer hat das Maul geöffnet, der andere geschlossen – zusammen sprechen sie Anfang und Ende aus.' },
    { id: 'samurai', title: 'Der Samurai',
      text: 'Das Wort „Samurai" kommt von einem Verb, das „dienen" bedeutet. Ein Krieger ohne Herrn hieß Rōnin – wörtlich „Wellenmensch", einer, der treibt.' },
    { id: 'sengoku', title: 'Die Zeit der streitenden Reiche',
      text: 'Über anderthalb Jahrhunderte kämpften die Fürstenhäuser um die Vorherrschaft. Erst Tokugawa Ieyasu einte das Land 1600 nach der Schlacht von Sekigahara.' },
    { id: 'ashigaru', title: 'Ashigaru',
      text: 'Die Fußsoldaten stellten das Gros der Heere. Mit Langspieß und Muskete bewaffnet, entschieden sie die Schlachten – nicht der berittene Einzelkämpfer.' },
    { id: 'ninja', title: 'Shinobi',
      text: 'Über die Shinobi ist weniger gesichert, als Geschichten vermuten lassen. Belegt sind Aufklärung, Sabotage und Botendienste – die schwarze Tracht ist eine Erfindung des Theaters.' },
    { id: 'noh', title: 'Nō und Kabuki',
      text: 'Im Nō-Theater tragen die Spieler Masken und bewegen sich äußerst langsam. Das lebhaftere Kabuki entstand später – gegründet von einer Tänzerin namens Izumo no Okuni.' },
    { id: 'haiku', title: 'Das Haiku',
      text: 'Ein Haiku umfasst drei Zeilen mit fünf, sieben und fünf Silben. Bashō machte die Form im 17. Jahrhundert zur ernsten Dichtung.' },
    { id: 'tea', title: 'Die Teezeremonie',
      text: 'Die Teezeremonie folgt vier Grundsätzen: Harmonie, Ehrfurcht, Reinheit und Stille. Der Weg zum Teehaus ist Teil der Zeremonie.' },
    { id: 'zen', title: 'Zen',
      text: 'Zen kam aus China und prägte die Kriegerkaste: Bogenschießen, Schwertkunst und Gartenbau wurden zu Übungswegen der Achtsamkeit.' },
    { id: 'garden', title: 'Der Steingarten',
      text: 'Im Steingarten von Ryōan-ji liegen fünfzehn Steine. Von keinem Standpunkt aus sind alle fünfzehn gleichzeitig zu sehen.' },
    { id: 'ukiyoe', title: 'Der Holzschnitt',
      text: 'Farbholzschnitte wie „Die große Welle" von Hokusai wurden in großer Auflage gedruckt. In Europa waren sie zeitweise so billig, dass man sie als Packpapier nutzte.' },
    { id: 'shinto', title: 'Shintō',
      text: 'Im Shintō wohnen Kami in Bergen, Bäumen, Flüssen – in allem Auffälligen. Ein rotes Torii markiert die Grenze zum heiligen Bezirk.' },
    { id: 'origami', title: 'Papier',
      text: 'Japanisches Washi-Papier ist so reißfest, dass man daraus Schiebewände, Laternen und sogar Rüstungsteile fertigte.' },
    { id: 'earthquake', title: 'Bauen im Erdbebenland',
      text: 'Hölzerne Pagoden überstehen Erdbeben seit über tausend Jahren. Ein frei schwingender Mittelpfeiler wirkt wie ein Gegengewicht.' },
    { id: 'rice', title: 'Reis als Währung',
      text: 'Das Einkommen eines Fürsten wurde in Koku gemessen – der Reismenge, die einen Menschen ein Jahr ernährt. Land bewertete man nicht in Fläche, sondern in Reis.' },
    { id: 'sakoku', title: 'Die geschlossene Zeit',
      text: 'Ab 1639 schottete sich Japan über zwei Jahrhunderte ab. Nur ein niederländischer Handelsposten auf der Insel Dejima blieb als Fenster nach Europa.' },
    { id: 'koi', title: 'Der Karpfen',
      text: 'Der Legende nach wird ein Karpfen, der den Wasserfall am Drachentor hinaufspringt, selbst zum Drachen. Deshalb steht der Koi für Beharrlichkeit.' },
    { id: 'kintsugi', title: 'Kintsugi',
      text: 'Zerbrochene Keramik wird mit Goldlack geklebt, statt die Bruchstellen zu verbergen. Das Gefäß gilt danach als wertvoller – die Geschichte gehört dazu.' },
    { id: 'yukionna', title: 'Yuki-onna',
      text: 'Die Schneefrau erscheint in Winternächten als Gestalt in Weiß. Wer ihr begegnet, erfriert – es sei denn, sie fasst Zuneigung.' },
    { id: 'tanuki', title: 'Der Tanuki',
      text: 'Der Marderhund gilt als Gestaltwandler und Schelm. Vor Wirtshäusern stehen seine Figuren, weil er Wohlstand bringen soll – meist mit einem Krug in der Hand.' },
    { id: 'daruma', title: 'Die Daruma-Puppe',
      text: 'Bei einer Daruma-Puppe malt man zu Beginn ein Auge aus und äußert einen Wunsch. Das zweite Auge folgt erst, wenn er erfüllt ist.' }
  ]);

  f.questions = f.questions.concat([
    { fact: 'yokai', q: 'Was bezeichnet der Begriff Yōkai?', answers: ['Die Wesen der japanischen Geisterwelt', 'Eine Schwertform', 'Die Ahnen einer Familie', 'Ein Fest im Frühling'], correct: 0 },
    { fact: 'kappa', q: 'Wo sitzt die Kraft eines Kappa?', answers: ['In einer wassergefüllten Schale auf dem Kopf', 'In seinem Panzer', 'In seinen Krallen', 'In seinem Schwanz'], correct: 0 },
    { fact: 'kappa', q: 'Wie kann man einen Kappa überlisten?', answers: ['Sich vor ihm verneigen, damit er zurückgrüßt', 'Ihm Reis anbieten', 'Ihn beim Namen rufen', 'Ihm ein Rätsel stellen'], correct: 0 },
    { fact: 'kitsune', q: 'Was bedeutet die Zahl der Schwänze bei einem Kitsune?', answers: ['Je mehr, desto älter und mächtiger', 'Je mehr, desto schwächer', 'Sie zeigt seinen Rang im Rudel', 'Sie hat keine Bedeutung'], correct: 0 },
    { fact: 'kitsune', q: 'Wofür ist der Kitsune besonders bekannt?', answers: ['Für seine Verwandlungskunst', 'Für seine Stärke', 'Für seine Heilkräfte', 'Für seinen Gesang'], correct: 0 },
    { fact: 'tengu', q: 'Wo hausen die Tengu?', answers: ['In den Bergen', 'In Flüssen', 'In verlassenen Tempeln', 'Auf dem Meer'], correct: 0 },
    { fact: 'tengu', q: 'Worin gelten Tengu als unübertroffen?', answers: ['Im Schwertkampf', 'Im Bogenschießen', 'In der Dichtung', 'Im Verwandeln'], correct: 0 },
    { fact: 'oni', q: 'Was ruft man beim Setsubun-Fest?', answers: ['„Oni raus, Glück herein!"', '„Der Frühling kommt!"', '„Ehre den Ahnen!"', '„Fort mit dem Winter!"'], correct: 0 },
    { fact: 'oni', q: 'Womit vertreibt man beim Setsubun die Oni?', answers: ['Mit gerösteten Sojabohnen', 'Mit Reiswein', 'Mit Glockenschlägen', 'Mit Feuer'], correct: 0 },
    { fact: 'orochi', q: 'Wie besiegte Susanoo die achtköpfige Schlange?', answers: ['Er betäubte sie mit acht Fässern Reiswein', 'Er erschlug sie im offenen Kampf', 'Er sperrte sie in einen Berg', 'Er überlistete sie mit einem Rätsel'], correct: 0 },
    { fact: 'orochi', q: 'Was forderte Yamata no Orochi jedes Jahr?', answers: ['Ein Mädchen', 'Die halbe Ernte', 'Ein Schwert', 'Einen Krieger'], correct: 0 },
    { fact: 'kusanagi', q: 'Wo fand Susanoo das Schwert Kusanagi?', answers: ['Im Schwanz der Schlange', 'Auf dem Grund eines Sees', 'In einem Schrein', 'Im Bauch eines Fisches'], correct: 0 },
    { fact: 'kusanagi', q: 'Was gehört zu den drei Reichsinsignien Japans?', answers: ['Schwert, Spiegel und Krummjuwel', 'Krone, Zepter und Reichsapfel', 'Fächer, Schwert und Siegel', 'Spiegel, Glocke und Trommel'], correct: 0 },
    { fact: 'komainu', q: 'Was ist bei den Komainu vor Schreinen besonders?', answers: ['Einer hat das Maul offen, der andere geschlossen', 'Sie sind immer aus Bronze', 'Sie stehen einzeln', 'Sie tragen Namen der Ahnen'], correct: 0 },
    { fact: 'samurai', q: 'Was bedeutet das Wort „Samurai" ursprünglich?', answers: ['Dienen', 'Kämpfen', 'Schützen', 'Herrschen'], correct: 0 },
    { fact: 'samurai', q: 'Wie nannte man einen Krieger ohne Herrn?', answers: ['Rōnin', 'Ashigaru', 'Shōgun', 'Daimyō'], correct: 0 },
    { fact: 'sengoku', q: 'Wer einte Japan nach der Schlacht von Sekigahara?', answers: ['Tokugawa Ieyasu', 'Oda Nobunaga', 'Minamoto no Yoritomo', 'Taira no Kiyomori'], correct: 0 },
    { fact: 'sengoku', q: 'In welchem Jahr fand die Schlacht von Sekigahara statt?', answers: ['1600', '1467', '1868', '1543'], correct: 0 },
    { fact: 'ashigaru', q: 'Wer stellte den größten Teil der Heere?', answers: ['Die Fußsoldaten, die Ashigaru', 'Berittene Samurai', 'Angeworbene Shinobi', 'Mönche'], correct: 0 },
    { fact: 'ashigaru', q: 'Womit waren die Ashigaru bewaffnet?', answers: ['Mit Langspieß und Muskete', 'Nur mit Katana', 'Mit Wurfnetzen', 'Mit Streitäxten'], correct: 0 },
    { fact: 'ninja', q: 'Was ist über die Shinobi tatsächlich belegt?', answers: ['Aufklärung, Sabotage und Botendienste', 'Ihre schwarze Tracht', 'Ihre Geheimschrift', 'Ihre Klosterorden'], correct: 0 },
    { fact: 'ninja', q: 'Woher stammt das Bild vom schwarz gekleideten Ninja?', answers: ['Aus dem Theater', 'Aus Chroniken der Sengoku-Zeit', 'Aus chinesischen Quellen', 'Aus Grabfunden'], correct: 0 },
    { fact: 'noh', q: 'Was kennzeichnet das Nō-Theater?', answers: ['Masken und sehr langsame Bewegungen', 'Schnelle Kampfszenen', 'Puppen statt Schauspieler', 'Gesang ohne Musik'], correct: 0 },
    { fact: 'noh', q: 'Wer gründete das Kabuki-Theater?', answers: ['Die Tänzerin Izumo no Okuni', 'Der Dichter Bashō', 'Ein Hofbeamter des Shōgun', 'Ein Zen-Mönch'], correct: 0 },
    { fact: 'haiku', q: 'Wie ist ein Haiku aufgebaut?', answers: ['Drei Zeilen mit fünf, sieben und fünf Silben', 'Vier Zeilen zu je sieben Silben', 'Zwei Zeilen ohne feste Zahl', 'Fünf Zeilen mit Reim'], correct: 0 },
    { fact: 'haiku', q: 'Wer machte das Haiku zur ernsten Dichtung?', answers: ['Bashō', 'Hokusai', 'Murasaki Shikibu', 'Sei Shōnagon'], correct: 0 },
    { fact: 'tea', q: 'Welche vier Grundsätze prägen die Teezeremonie?', answers: ['Harmonie, Ehrfurcht, Reinheit und Stille', 'Mut, Treue, Ehre und Fleiß', 'Erde, Wasser, Feuer und Luft', 'Sehen, Hören, Riechen und Schmecken'], correct: 0 },
    { fact: 'zen', q: 'Woher kam der Zen-Buddhismus nach Japan?', answers: ['Aus China', 'Aus Indien direkt', 'Aus Korea allein', 'Er entstand in Japan'], correct: 0 },
    { fact: 'garden', q: 'Was ist am Steingarten von Ryōan-ji besonders?', answers: ['Von keinem Punkt aus sieht man alle fünfzehn Steine', 'Er enthält keine Steine, nur Sand', 'Er wird täglich umgestaltet', 'Er ist kreisrund'], correct: 0 },
    { fact: 'ukiyoe', q: 'Wer schuf „Die große Welle"?', answers: ['Hokusai', 'Hiroshige', 'Utamaro', 'Sesshū'], correct: 0 },
    { fact: 'ukiyoe', q: 'Wofür wurden japanische Holzschnitte in Europa zeitweise verwendet?', answers: ['Als Packpapier', 'Als Tapete am Hof', 'Als Spielkarten', 'Als Zahlungsmittel'], correct: 0 },
    { fact: 'shinto', q: 'Was markiert ein rotes Torii?', answers: ['Die Grenze zum heiligen Bezirk', 'Den Sitz eines Fürsten', 'Eine Straßenkreuzung', 'Ein Grab'], correct: 0 },
    { fact: 'shinto', q: 'Wo wohnen die Kami nach shintoistischer Vorstellung?', answers: ['In Bergen, Bäumen und Flüssen', 'Nur in Tempeln', 'Im Himmel allein', 'In den Ahnentafeln'], correct: 0 },
    { fact: 'origami', q: 'Was fertigte man aus japanischem Washi-Papier?', answers: ['Schiebewände, Laternen und Rüstungsteile', 'Nur Bücher', 'Segel für Schiffe', 'Geldscheine'], correct: 0 },
    { fact: 'earthquake', q: 'Warum überstehen hölzerne Pagoden Erdbeben?', answers: ['Ein frei schwingender Mittelpfeiler wirkt als Gegengewicht', 'Sie stehen auf Sandbetten', 'Ihr Holz ist besonders elastisch', 'Sie sind sehr niedrig gebaut'], correct: 0 },
    { fact: 'rice', q: 'Worin wurde das Einkommen eines Fürsten gemessen?', answers: ['In Koku – der Reismenge für einen Menschen im Jahr', 'In Goldstücken', 'In Quadratmeilen Land', 'In der Zahl seiner Krieger'], correct: 0 },
    { fact: 'sakoku', q: 'Was blieb während der Abschottung Japans als Fenster nach Europa?', answers: ['Ein niederländischer Handelsposten auf Dejima', 'Ein portugiesischer Hafen in Nagasaki', 'Eine spanische Mission', 'Gar nichts'], correct: 0 },
    { fact: 'sakoku', q: 'Wie lange schottete sich Japan ab?', answers: ['Über zwei Jahrhunderte', 'Etwa zwanzig Jahre', 'Rund fünfzig Jahre', 'Fast tausend Jahre'], correct: 0 },
    { fact: 'koi', q: 'Wofür steht der Koi in der Legende?', answers: ['Für Beharrlichkeit', 'Für Reichtum', 'Für Schnelligkeit', 'Für Weisheit'], correct: 0 },
    { fact: 'koi', q: 'Was wird aus einem Karpfen, der das Drachentor hinaufspringt?', answers: ['Ein Drache', 'Ein Kami', 'Ein Tengu', 'Ein Mensch'], correct: 0 },
    { fact: 'kintsugi', q: 'Was geschieht beim Kintsugi mit zerbrochener Keramik?', answers: ['Die Bruchstellen werden mit Goldlack sichtbar geklebt', 'Sie wird eingeschmolzen', 'Sie wird übermalt', 'Die Scherben werden vergraben'], correct: 0 },
    { fact: 'kintsugi', q: 'Wie gilt ein mit Kintsugi geflicktes Gefäß?', answers: ['Als wertvoller als zuvor', 'Als unbrauchbar', 'Als unrein', 'Als billiger Ersatz'], correct: 0 },
    { fact: 'yukionna', q: 'Wann erscheint die Yuki-onna?', answers: ['In Winternächten', 'Zur Kirschblüte', 'Bei Vollmond im Sommer', 'Vor Erdbeben'], correct: 0 },
    { fact: 'tanuki', q: 'Warum stehen Tanuki-Figuren vor Wirtshäusern?', answers: ['Er soll Wohlstand bringen', 'Er vertreibt Diebe', 'Er zeigt die Öffnungszeit an', 'Er ist das Wappen der Zunft'], correct: 0 },
    { fact: 'daruma', q: 'Wann malt man das zweite Auge einer Daruma-Puppe aus?', answers: ['Wenn der Wunsch erfüllt ist', 'Am Neujahrstag', 'Sofort beim Kauf', 'Nie'], correct: 0 },
    { fact: 'katana', q: 'Warum bricht eine gefaltete Klinge nicht so leicht?', answers: ['Der weichere Kern fängt die Spannung auf', 'Sie ist besonders dick', 'Sie wird kalt geschmiedet', 'Sie enthält Silber'], correct: 0 },
    { fact: 'castle', q: 'Was blieb bei einem Brand einer japanischen Burg meist stehen?', answers: ['Die Steinmauer', 'Der Hauptturm', 'Das Dach', 'Die Tore'], correct: 0 },
    { fact: 'onna', q: 'Was belegen Grabfunde über Frauen des Kriegerstandes?', answers: ['Manche standen auf dem Schlachtfeld', 'Sie trugen nie Waffen', 'Sie lebten getrennt von den Männern', 'Sie führten die Heere an'], correct: 0 },
    { fact: 'hyakki', q: 'Wie oft zieht die Nachtparade der Überlieferung nach?', answers: ['In Sommernächten, alle hundert Jahre besonders', 'Jede Vollmondnacht', 'Einmal im Frühling', 'Nur bei Sonnenfinsternis'], correct: 0 },
    { fact: 'tomoe', q: 'Wie beschreibt das Heike-Monogatari Tomoe Gozen?', answers: ['Als Kriegerin, die es mit tausend aufnahm', 'Als Dichterin am Hofe', 'Als Priesterin eines Schreins', 'Als Tochter des Kaisers'], correct: 0 }
  ]);
})(window);
